### obtener todos los productos
GET http://localhost:3000/api/productos

### obtener un producto
GET http://localhost:3000/api/productos/1

### crear un nuevo producto
POST http://localhost:3000/api/productos
Content-Type: application/json

{
  "idProducto": "1",
  "descripcion": "Pantalon de Mozzi v5",
  "precio": 24000,
  "idTipo": 4,
  "stock": 10,
  "imagen": "una url cualquiera"
}

### modificar un producto con put
PUT http://localhost:3000/api/productos/14
Content-Type: application/json

{
  "idProducto": "14",
  "descripcion": "Pantalon de mozzi modificado con put",
  "precio": 150000,
  "idTipo": 1,
  "stock": 105,
  "imagen": "una url cualquiera modificada con put"
}

### modificar un producto con patch
PATCH http://localhost:3000/api/productos/14
Content-Type: application/json

{
  "idProducto": "14",
  "descripcion": "Pantalon de mozzi modificado con patch",
  "precio": 150000,
  "imagen": "una url cualquiera modificada con patch"
}

### eliminar un producto
DELETE http://localhost:3000/api/productos/9