### obtener todos los productos
GET http://localhost:3000/api/productos

### obtener un producto
GET http://localhost:3000/api/productos/1

### crear un nuevo producto
POST http://localhost:3000/api/productos
Content-Type: application/json

{
  "idProducto": "2",
  "descripcion": "Pantalon de Mozzi",
  "precio": 10000,
  "idTipo": 2,
  "stock": 10,
  "imagen": "otra url cualquiera"
}